//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Azure_Assignment.EF
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Feedbacks
    {
        [DisplayName("Feedback ID")]
        public int FeedbackID { get; set; }
        [DisplayName("Feedback name")]
        public string FeedbackName { get; set; }
        public string Email { get; set; }
        public string Content { get; set; }
        [DisplayName("Feedback date")]
        public Nullable<System.DateTime> FeedBackDate { get; set; }
        public Nullable<int> ProductID { get; set; }

        public virtual Products Products { get; set; }
    }
}
