//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Azure_Assignment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Importation
    {
        public int ImportationID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public string Username { get; set; }
        public Nullable<System.DateTime> ImportDate { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<int> Quantity { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Product Product { get; set; }
    }
}
